### ISSUE TITLE
Currently using Prod_days == 0 as the filter for CO2_only wells

### ISSUE THREAD

**Issue by jevans-cdphe** [jevans-cdphe/oip-ecmc#2]
This is likely not correct and needs further inspection of other datasets to come up with a better heuristic.

**Comment by bhmiel-cdphe** [comment]
Better way to to this is use the `gas_type` field in the `Colorado Well Completions` table.  Many of these are blank, but there are several which have `CO2` and `HELIUM` which can be filtered out.  We have to assume the blank ones are NG.  

Nevertheless, Prod_days == 0 is still a good filter to have, as we only want to aggregate over wells that had production, no?  Maybe numeric values >0 for `oil_prod` and `gas_prod` is better.....

There are 4 wells with `Helium` as the type, only 1 of which is `PR`.  
There are 194 wells with `CO2`, all with many different status codes.  
There is also one well with `gas_type` of `OTHER`, but its status is `SI` meaning Shut-in, so that shouldn't matter.

**Comment by jevans-cdphe** [comment]
Internal CDPHE issues are now being tracked in Azure DevOps. GitHub issues are for public submissions going forward.
